### PR TITLE
Updated insert() using pg-format, #15

### PR DESCRIPTION
**Pull request by lakhassane**

### CODE REVIEW

**Comment by lakhassane** [comment]
@taylordowns2000 please wait for the commits for upsert before you handle this PR.

**Comment by lakhassane** [comment]
@taylordowns2000 feel free to review

**Review by taylordowns2000 — COMMENTED** [review]
This looks clean! Thanks @lakhassane . I'm waiting on your test for the `wcs-consocsci` jobs and will then merge and prepare the next verison of this adaptor.

**Review by taylordowns2000 — APPROVED** [review]
In business!

**Pull request merged**
